version: "3"

services:
  db:
    container_name: piggy_flow_db
    image: mariadb:10.3
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_HOST: "%"
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      TZ: ${MYSQL_TIMEZONE} 
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - internal

  pma:
    container_name: piggy_flow_pma
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - external
      - internal

  api:
    container_name: piggy_flow_api
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    volumes:
      - ./backend/:/usr/src/app
    command: npm run start:dev
    depends_on:
      - db
    ports:
      - ${PORT}:3000
    networks:
      - external
      - internal

networks:
  external:
    external: true
  internal:
    external: false
