version: "3"

services:
  db:
    container_name: piggy_flow_db
    image: mariadb:10.3
    restart: unless-stopped
    volumes:
      - piggy_flow_data:/var/lib/mysql
    env_file:
      - .env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - internal

  api:
    container_name: piggy_flow_api
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env.backend
    depends_on:
      - db
    ports:
      - ${PORT}:3000
    volumes:
      - ./uploads:/app/uploads
    networks:
      - external
      - internal

networks:
  external:
    external: true
  internal:
    external: false

volumes:
  piggy_flow_data:
