version: "3"

services:
  pma:
    container_name: piggy_flow_pma
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - external
      - internal
  api:
    build:
      target: development
    volumes:
      - ./backend/:/app

networks:
  external:
    external: true
  internal:
    external: false
